spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/seareaurl
#    url: jdbc:h2:~/seareaurl
    driver-class-name: org.h2.Driver
    username: sa2
    password:
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always


# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace

